name: Super Contribution Filler

on:
  workflow_dispatch: # Klik tombol "Run workflow" di tab Actions

jobs:
  fill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git Config
        run: |
          git config --global user.name "akangumam"
          git config --global user.email "akangumam@users.noreply.github.com"

      - name: Fill 90 Days of Contributions
        run: |
          # Loop untuk 90 hari ke belakang
          for i in {90..0}
          do
            # Membuat 3-7 commit acak setiap harinya agar terlihat padat
            NUM_COMMITS=$(( ( RANDOM % 5 )  + 3 ))
            for j in $(seq 1 $NUM_COMMITS)
            do
              D=$(date -d "$i days ago" +%Y-%m-%dT%H:%M:%S)
              GIT_AUTHOR_DATE="$D" GIT_COMMITTER_DATE="$D" git commit --allow-empty -m "Aesthetic commit" --date "$D"
            done
          done

      - name: Push Changes
        run: |
          git push origin main
