name: Ultimate Contribution Filler

on:
  workflow_dispatch:

jobs:
  fill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git Config
        run: |
          git config --global user.name "akangumam"
          git config --global user.email "akangumam@users.noreply.github.com"

      - name: Fill Random Contributions (1 Year)
        run: |
          # Melakukan 300 commit pada tanggal acak dalam 365 hari terakhir
          for i in {1..300}
          do
            # Pilih hari acak antara 0 sampai 365
            RAND_DAY=$(( RANDOM % 365 ))
            D=$(date -d "$RAND_DAY days ago" +%Y-%m-%dT%H:%M:%S)
            GIT_AUTHOR_DATE="$D" GIT_COMMITTER_DATE="$D" git commit --allow-empty -m "Aesthetic random commit" --date "$D"
          done

      - name: Push Changes
        run: |
          git push origin main
